# Name of this GitHub Actions workflow.
name: Semgrep

on:
  push:
    branches: ["master", "main"]
    paths:
    - .github/workflows/sem.yml

jobs:
  semTest:
    runs-on: ubuntu-latest
    steps:
      - name: Run Semgrep
        env:
          SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
        run: |
          docker run  --name semgrep --rm -v "${PWD}:/src" semgrep/semgrep
          
